"""create_files_table

Revision ID: cb1b55d9dfcc
Revises: 34b45a8461bb
Create Date: 2025-12-05 15:53:25.240852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb1b55d9dfcc"
down_revision: Union[str, None] = "34b45a8461bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_type", sa.String(length=20), nullable=False),
        sa.Column("storage_bucket", sa.String(length=100), nullable=True),
        sa.Column("storage_region", sa.String(length=50), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("scan_status", sa.String(length=20), nullable=False),
        sa.Column("file_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_files_created_at"), "files", ["created_at"], unique=False)
    op.create_index(op.f("ix_files_deleted_at"), "files", ["deleted_at"], unique=False)
    op.create_index("ix_files_document_deleted", "files", ["document_id", "is_deleted"], unique=False)
    op.create_index(op.f("ix_files_document_id"), "files", ["document_id"], unique=False)
    op.create_index(op.f("ix_files_file_hash"), "files", ["file_hash"], unique=False)
    op.create_index(op.f("ix_files_filename"), "files", ["filename"], unique=False)
    op.create_index("ix_files_hash_size", "files", ["file_hash", "file_size"], unique=False)
    op.create_index(op.f("ix_files_is_deleted"), "files", ["is_deleted"], unique=False)
    op.create_index("ix_files_mime_type", "files", ["mime_type"], unique=False)
    op.create_index(op.f("ix_files_uploaded_by_id"), "files", ["uploaded_by_id"], unique=False)
    op.create_index("ix_files_workspace_deleted", "files", ["workspace_id", "is_deleted"], unique=False)
    op.create_index(op.f("ix_files_workspace_id"), "files", ["workspace_id"], unique=False)
    op.create_unique_constraint(None, "document_versions", ["id"])
    op.create_unique_constraint(None, "documents", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="unique")
    op.drop_constraint(None, "document_versions", type_="unique")
    op.drop_index(op.f("ix_files_workspace_id"), table_name="files")
    op.drop_index("ix_files_workspace_deleted", table_name="files")
    op.drop_index(op.f("ix_files_uploaded_by_id"), table_name="files")
    op.drop_index("ix_files_mime_type", table_name="files")
    op.drop_index(op.f("ix_files_is_deleted"), table_name="files")
    op.drop_index("ix_files_hash_size", table_name="files")
    op.drop_index(op.f("ix_files_filename"), table_name="files")
    op.drop_index(op.f("ix_files_file_hash"), table_name="files")
    op.drop_index(op.f("ix_files_document_id"), table_name="files")
    op.drop_index("ix_files_document_deleted", table_name="files")
    op.drop_index(op.f("ix_files_deleted_at"), table_name="files")
    op.drop_index(op.f("ix_files_created_at"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
