"""create_presence_tables

Revision ID: 795d0204f888
Revises: cb1b55d9dfcc
Create Date: 2025-12-05 16:17:41.591096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "795d0204f888"
down_revision: Union[str, None] = "cb1b55d9dfcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("current_workspace_id", sa.UUID(), nullable=True),
        sa.Column("current_document_id", sa.UUID(), nullable=True),
        sa.Column("session_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["current_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["current_workspace_id"], ["workspaces.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_user_sessions_connection_id"), "user_sessions", ["connection_id"], unique=True)
    op.create_index(op.f("ix_user_sessions_created_at"), "user_sessions", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_user_sessions_current_document_id"), "user_sessions", ["current_document_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_current_workspace_id"), "user_sessions", ["current_workspace_id"], unique=False
    )
    op.create_index("ix_user_sessions_document", "user_sessions", ["current_document_id", "is_active"], unique=False)
    op.create_index(op.f("ix_user_sessions_is_active"), "user_sessions", ["is_active"], unique=False)
    op.create_index("ix_user_sessions_user_active", "user_sessions", ["user_id", "is_active"], unique=False)
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_index("ix_user_sessions_workspace", "user_sessions", ["current_workspace_id", "is_active"], unique=False)
    op.create_table(
        "document_presence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_editing", sa.Boolean(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
        sa.Column("cursor_line", sa.Integer(), nullable=True),
        sa.Column("cursor_column", sa.Integer(), nullable=True),
        sa.Column("selection_start_line", sa.Integer(), nullable=True),
        sa.Column("selection_start_column", sa.Integer(), nullable=True),
        sa.Column("selection_end_line", sa.Integer(), nullable=True),
        sa.Column("selection_end_column", sa.Integer(), nullable=True),
        sa.Column("presence_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["user_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_document_presence_created_at"), "document_presence", ["created_at"], unique=False)
    op.create_index("ix_document_presence_doc_active", "document_presence", ["document_id", "is_active"], unique=False)
    op.create_index("ix_document_presence_doc_user", "document_presence", ["document_id", "user_id"], unique=True)
    op.create_index(op.f("ix_document_presence_document_id"), "document_presence", ["document_id"], unique=False)
    op.create_index(op.f("ix_document_presence_is_active"), "document_presence", ["is_active"], unique=False)
    op.create_index(op.f("ix_document_presence_session_id"), "document_presence", ["session_id"], unique=False)
    op.create_index("ix_document_presence_user", "document_presence", ["user_id", "is_active"], unique=False)
    op.create_index(op.f("ix_document_presence_user_id"), "document_presence", ["user_id"], unique=False)
    op.create_unique_constraint(None, "files", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "files", type_="unique")
    op.drop_index(op.f("ix_document_presence_user_id"), table_name="document_presence")
    op.drop_index("ix_document_presence_user", table_name="document_presence")
    op.drop_index(op.f("ix_document_presence_session_id"), table_name="document_presence")
    op.drop_index(op.f("ix_document_presence_is_active"), table_name="document_presence")
    op.drop_index(op.f("ix_document_presence_document_id"), table_name="document_presence")
    op.drop_index("ix_document_presence_doc_user", table_name="document_presence")
    op.drop_index("ix_document_presence_doc_active", table_name="document_presence")
    op.drop_index(op.f("ix_document_presence_created_at"), table_name="document_presence")
    op.drop_table("document_presence")
    op.drop_index("ix_user_sessions_workspace", table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index("ix_user_sessions_user_active", table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_is_active"), table_name="user_sessions")
    op.drop_index("ix_user_sessions_document", table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_current_workspace_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_current_document_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_created_at"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_connection_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
