"""create_folders_table_and_add_folder_id_to_documents

Revision ID: f0e0835707b7
Revises: 795d0204f888
Create Date: 2025-12-08 18:25:00.035433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0e0835707b7"
down_revision: Union[str, None] = "795d0204f888"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_expanded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_folders_created_at"), "folders", ["created_at"], unique=False)
    op.create_index(op.f("ix_folders_created_by_id"), "folders", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_folders_deleted_at"), "folders", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_folders_is_deleted"), "folders", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_folders_name"), "folders", ["name"], unique=False)
    op.create_index("ix_folders_parent", "folders", ["parent_id", "position"], unique=False)
    op.create_index(op.f("ix_folders_parent_id"), "folders", ["parent_id"], unique=False)
    op.create_index("ix_folders_workspace_deleted", "folders", ["workspace_id", "is_deleted"], unique=False)
    op.create_index(op.f("ix_folders_workspace_id"), "folders", ["workspace_id"], unique=False)
    op.create_unique_constraint(None, "document_presence", ["id"])
    op.add_column("documents", sa.Column("folder_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_documents_folder_id"), "documents", ["folder_id"], unique=False)
    op.create_foreign_key(None, "documents", "folders", ["folder_id"], ["id"], ondelete="SET NULL")
    op.create_unique_constraint(None, "user_sessions", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_sessions", type_="unique")
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_folder_id"), table_name="documents")
    op.drop_column("documents", "folder_id")
    op.drop_constraint(None, "document_presence", type_="unique")
    op.drop_index(op.f("ix_folders_workspace_id"), table_name="folders")
    op.drop_index("ix_folders_workspace_deleted", table_name="folders")
    op.drop_index(op.f("ix_folders_parent_id"), table_name="folders")
    op.drop_index("ix_folders_parent", table_name="folders")
    op.drop_index(op.f("ix_folders_name"), table_name="folders")
    op.drop_index(op.f("ix_folders_is_deleted"), table_name="folders")
    op.drop_index(op.f("ix_folders_deleted_at"), table_name="folders")
    op.drop_index(op.f("ix_folders_created_by_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_created_at"), table_name="folders")
    op.drop_table("folders")
    # ### end Alembic commands ###
