"""create_documents_and_versions_tables

Revision ID: 34b45a8461bb
Revises: b521f9b4cb4e
Create Date: 2025-12-05 15:36:25.844122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "34b45a8461bb"
down_revision: Union[str, None] = "b521f9b4cb4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("doc_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False)
    op.create_index(op.f("ix_documents_created_by_id"), "documents", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_documents_deleted_at"), "documents", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_documents_is_deleted"), "documents", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_documents_is_template"), "documents", ["is_template"], unique=False)
    op.create_index(op.f("ix_documents_slug"), "documents", ["slug"], unique=False)
    op.create_index("ix_documents_tags", "documents", ["tags"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_documents_title"), "documents", ["title"], unique=False)
    op.create_index("ix_documents_title_search", "documents", ["title"], unique=False)
    op.create_index("ix_documents_workspace_created", "documents", ["workspace_id", "created_at"], unique=False)
    op.create_index("ix_documents_workspace_deleted", "documents", ["workspace_id", "is_deleted"], unique=False)
    op.create_index(op.f("ix_documents_workspace_id"), "documents", ["workspace_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("change_summary", sa.String(length=500), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("version_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("ix_document_versions_created", "document_versions", ["document_id", "created_at"], unique=False)
    op.create_index(op.f("ix_document_versions_created_at"), "document_versions", ["created_at"], unique=False)
    op.create_index(op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False)
    op.create_index(
        "ix_document_versions_document_version", "document_versions", ["document_id", "version_number"], unique=True
    )
    op.create_unique_constraint(None, "workspace_members", ["id"])
    op.create_unique_constraint(None, "workspaces", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workspaces", type_="unique")
    op.drop_constraint(None, "workspace_members", type_="unique")
    op.drop_index("ix_document_versions_document_version", table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_created_at"), table_name="document_versions")
    op.drop_index("ix_document_versions_created", table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_documents_workspace_id"), table_name="documents")
    op.drop_index("ix_documents_workspace_deleted", table_name="documents")
    op.drop_index("ix_documents_workspace_created", table_name="documents")
    op.drop_index("ix_documents_title_search", table_name="documents")
    op.drop_index(op.f("ix_documents_title"), table_name="documents")
    op.drop_index("ix_documents_tags", table_name="documents", postgresql_using="gin")
    op.drop_index(op.f("ix_documents_slug"), table_name="documents")
    op.drop_index(op.f("ix_documents_is_template"), table_name="documents")
    op.drop_index(op.f("ix_documents_is_deleted"), table_name="documents")
    op.drop_index(op.f("ix_documents_deleted_at"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_by_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
