"""create_workspaces_and_members_tables

Revision ID: b521f9b4cb4e
Revises: 0b9963d0e9fd
Create Date: 2025-12-05 13:25:28.625121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b521f9b4cb4e"
down_revision: Union[str, None] = "0b9963d0e9fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_created_at"), "workspaces", ["created_at"], unique=False)
    op.create_index(op.f("ix_workspaces_deleted_at"), "workspaces", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_workspaces_is_archived"), "workspaces", ["is_archived"], unique=False)
    op.create_index(op.f("ix_workspaces_is_deleted"), "workspaces", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_workspaces_name"), "workspaces", ["name"], unique=False)
    op.create_index("ix_workspaces_owner_deleted", "workspaces", ["owner_id", "is_deleted"], unique=False)
    op.create_index(op.f("ix_workspaces_owner_id"), "workspaces", ["owner_id"], unique=False)
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_index("ix_workspaces_slug_deleted", "workspaces", ["slug", "is_deleted"], unique=False)
    op.create_table(
        "workspace_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("OWNER", "ADMIN", "EDITOR", "VIEWER", name="workspace_role"), nullable=False),
        sa.Column("invited_by_id", sa.UUID(), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["invited_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_workspace_members_created_at"), "workspace_members", ["created_at"], unique=False)
    op.create_index(op.f("ix_workspace_members_deleted_at"), "workspace_members", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_workspace_members_is_deleted"), "workspace_members", ["is_deleted"], unique=False)
    op.create_index("ix_workspace_members_user_deleted", "workspace_members", ["user_id", "is_deleted"], unique=False)
    op.create_index(op.f("ix_workspace_members_user_id"), "workspace_members", ["user_id"], unique=False)
    op.create_index(
        "ix_workspace_members_user_workspace", "workspace_members", ["user_id", "workspace_id"], unique=True
    )
    op.create_index(
        "ix_workspace_members_workspace_deleted", "workspace_members", ["workspace_id", "is_deleted"], unique=False
    )
    op.create_index(op.f("ix_workspace_members_workspace_id"), "workspace_members", ["workspace_id"], unique=False)
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_index(op.f("ix_workspace_members_workspace_id"), table_name="workspace_members")
    op.drop_index("ix_workspace_members_workspace_deleted", table_name="workspace_members")
    op.drop_index("ix_workspace_members_user_workspace", table_name="workspace_members")
    op.drop_index(op.f("ix_workspace_members_user_id"), table_name="workspace_members")
    op.drop_index("ix_workspace_members_user_deleted", table_name="workspace_members")
    op.drop_index(op.f("ix_workspace_members_is_deleted"), table_name="workspace_members")
    op.drop_index(op.f("ix_workspace_members_deleted_at"), table_name="workspace_members")
    op.drop_index(op.f("ix_workspace_members_created_at"), table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_index("ix_workspaces_slug_deleted", table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_owner_id"), table_name="workspaces")
    op.drop_index("ix_workspaces_owner_deleted", table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_name"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_is_deleted"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_is_archived"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_deleted_at"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_created_at"), table_name="workspaces")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
